### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by isaachier** [allenday/nanostream-dataflow#104]
Should be `BUFFER_SIZE` not `BUFFER_SZIE`.

https://github.com/allenday/nanostream-dataflow/blob/3e3028bd2a41db81713a333e807525bfbb355d02/NanostreamDataflowMain/src/main/java/com/google/allenday/nanostream/util/FastQUtils.java#L22

**Comment by obsh** [comment]
Thank you, fixed.
