### ISSUE TITLE
implement multi-record reading for fastq files

### ISSUE THREAD

**Issue by allenday** [allenday/nanostream-dataflow#16]
Current implementation accepts only first 4 lines in fastq file and emits a single record.

We can add a loop here to output multiple fastq records.

See:
https://github.com/allenday/nanostream-dataflow/blob/f5cb815f7a406946b5334870d789bda67472ab47/NanostreamDataflowMain/src/main/java/com/theappsolutions/nanostream/fastq/ParseFastQFn.java#L25

**Comment by obsh** [comment]
Resolved in #28
