### ISSUE TITLE
Tips are not shown after clicking on the "?" sign in the UI

### ISSUE THREAD

**Issue by obsh** [allenday/nanostream-dataflow#165]
Clicking has no effect. After some time I've discovered that tooltip is shown on "hover".
I believe it can be a bit confusing. Let's show tooltip on "click" event too.

![image](https://user-images.githubusercontent.com/1974420/76985473-f0660100-6948-11ea-8cef-b1ba01163ebc.png)

**Comment by vedmedka** [comment]
fix: https://github.com/allenday/nanostream-dataflow/pull/170
