### ISSUE TITLE
move bucket to publication location, update permissions as "request pays"

### ISSUE THREAD

**Issue by allenday** [allenday/nanostream-dataflow#18]
https://github.com/allenday/nanostream-dataflow/blob/e6d0fce6570165e3bd24d59b8a6f3dbc284f904d/aligner/provision_species.sh#L14

see:
https://cloud.google.com/storage/docs/requester-pays

I've created a new project `nanostream-dataflow` where we can put all artifacts for publication.

**Comment by obsh** [comment]
@allenday could you grant me access to the new project, please

**Comment by allenday** [comment]
done
