### ISSUE TITLE
Provide a color scheme for coloring bacterial species

### ISSUE THREAD

**Issue by lachlancoin** [allenday/nanostream-dataflow#24]

**Comment by lachlancoin** [comment]
I have written an algorithm for calculating colors for each species listed in the speciesIndex.  The results are uploaded as a modified speciesIndex file with an extra column on the end here:
gs://nano-stream/CombinedDatabases/speciesIndex
Also I have a slug.txt file:
gs://nano-stream/CombinedDatabases/slug.txt

I calculate this slug as follows

private static final Pattern NONLATIN = Pattern.compile("[^\\w-]");
private static final Pattern WHITESPACE = Pattern.compile("[\\s]");
public static String toSlug(String input) {
  Matcher matcher = WHITESPACE.matcher(input);
  for(int i=0; matcher.find(); i++) {
	 int st = matcher.start();
	 if(i==1){
		 input = input.substring(0,st);
		 break;
	 }
  }
  
 
  String nowhitespace = WHITESPACE.matcher(input).replaceAll("_");
  String normalized = Normalizer.normalize(nowhitespace, Form.NFD);
  String slug = NONLATIN.matcher(normalized).replaceAll("");
  return slug.toLowerCase(Locale.ENGLISH);
}


This is based on assembly_summary.txt files from here: ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/assembly_summary.txt
And the NCBI commontree resource.

**Comment by obsh** [comment]
Great, will use this in visualization in #27
