### ISSUE TITLE
retrieve bwa files from prod location

### ISSUE THREAD

**Issue by allenday** [allenday/nanostream-dataflow#41]
https://github.com/allenday/nanostream-dataflow/blob/ef69572d655632c1f567cdbda4596493733725b9/aligner/provision_species.sh#L14

**Comment by obsh** [comment]
@allenday please merge allenday/bwa-http-docker#3

**Comment by obsh** [comment]
> @allenday please merge [allenday/bwa-http-docker#3](https://github.com/allenday/bwa-http-docker/pull/3)

it won't work without new version of Docker container

**Comment by allenday** [comment]
merged

**Comment by obsh** [comment]
Image `allenday/bwa-http-docker:http` is not updated on Dockerhub. @allenday could you make a build with a latest version from the repository.
