### ISSUE TITLE
Any interest in pubsub monitoring app?

### ISSUE THREAD

**Issue by Firedrops** [allenday/nanostream-dataflow#59]
I have this adapted code from Google's code samples that allows us to monitor if PubSub is functioning, our version can be seen [here](https://upload-watcher-dot-nano-stream1.appspot.com/), useful when troubleshooting previously when I was trying to get the dataflow command working.

Would this be a helpful addition to the main branch of the project? If so I can push it..

**Comment by obsh** [comment]
Yes, I think it could be useful. There were at least several times where I needed to check what's going into PubSub subscription.

**Comment by Firedrops** [comment]
I'm not sure how to `pull` only certain files, don't want to accidentally overwrite all your variables with those in my fork. The app's files are [here](https://github.com/Firedrops/nanostream-dataflow/blob/master/pubsub_monitor), feel free to copy them and merge into allenday:master.

**Comment by Firedrops** [comment]
also, it might be helpful if we could somehow reverse the order. Right now, the latest messages are added at the bottom of the page, which may be problematic with real-time reads with high rates of uploads.

**Comment by Firedrops** [comment]
Merged in #106
