### ISSUE TITLE
Provisioning scripts cleanup (-c) jump to setup if firewall not found

### ISSUE THREAD

**Issue by Firedrops** [allenday/nanostream-dataflow#62]
This often happens when I cleanup both provisioning clusters consecutively.

The first cleanup (i.e. `./provision_species.sh -c`)will also delete the shared firewall rule of `allow-http`. The second cleanup i.e. `./provision_resistance_genes.sh -c`) will report a this as a missing rule:

```
ERROR: (gcloud.compute.firewall-rules.delete) Could not fetch resource:
 - The resource 'projects/nano-stream1/global/firewalls/allow-http' was not found
```

 then jump immediately to setting up a new provisioning cluster:

```
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
```

Even if I cancel with `ctrl + c` immediately, some setup will have been started, e.g. template creation, managed instance group, sometimes health checks, so it doesn't end in a clean slate.

Side question, is it possible to automate all the `y` prompts during cleanup?

**Comment by allenday** [comment]
you can prefix with "yes |"
