### ISSUE TITLE
New databases available

### ISSUE THREAD

**Issue by lachlancoin** [allenday/nanostream-dataflow#70]
In the gs://nano-stream1/Databases directory there are now three directories:
1 CombinedDatabases  which we have been using
2. Bacteria_Virus_Archaea   - this has no human and better archaea coverage
3. CassavaDatabase  this is virus  +bacteria + cassava

I would suggest moving to  Bacteria_Virus_Archaea for metagenomic apps (.e.g waste water).   Cassava good for Cassava example.

**Comment by lachlancoin** [comment]
By the way,no need to redo any analyses on your side.  Larry and I can work on getting results with these databases

**Comment by allenday** [comment]
already copied data gs://nanostream-dataflow-demo-data
