### ISSUE TITLE
New dogbite dataset spiked with publicly available reads

### ISSUE THREAD

**Issue by lachlancoin** [allenday/nanostream-dataflow#71]
As suggested by @allenday I spiked in NA12889 reads into the human-purged EDTA dataset.

It is available here:
gs://nano-stream1/test/20180326_EDTABloodcollection

**Comment by lachlancoin** [comment]
Note that all the human reads have a later timestamp than all bacterial reads

**Comment by lachlancoin** [comment]
I have added a spiked dataset here too (this is the s. aureus capture dataset)
gs://nano-stream1/test/20170731_GP01_MNP

**Comment by allenday** [comment]
ok, we copied it over to 1_Dogbite
