### ISSUE TITLE
Single .fastq files generating multiple Firestore documents

### ISSUE THREAD

**Issue by Firedrops** [allenday/nanostream-dataflow#74]
Previously encountered in #23 at [this comment](https://github.com/allenday/nanostream-dataflow/issues/23#issuecomment-463473930_), now again in #73 with `test_Cassava_KE.barcode1_KE.barcode1.fasta` test. 2 `resultDocument`s are generated back-to-back from the same read.

![image](https://user-images.githubusercontent.com/31351436/52931921-e23a5f80-3399-11e9-8570-1eb852c7f650.png)

You can see the sunburst [here](https://nano-stream1.appspot.com/?c=new_scanning_species_sequences_statistic&d=resultDocument--2019-02-18T02-21-45UTC) and [here](https://nano-stream1.appspot.com/?c=new_scanning_species_sequences_statistic&d=resultDocument--2019-02-18T02-22-20UTC). The later document appears to be more 'complete' than the earlier one, with additional species.

**Comment by Pseverin** [comment]
Fixed in https://github.com/allenday/nanostream-dataflow/pull/75
