### ISSUE TITLE
provisioning node Server Error

### ISSUE THREAD

**Issue by Firedrops** [allenday/nanostream-dataflow#81]
This has been happening for all new deployments since yesterday (before last night's commits), I thought it would be temporary but it's still ongoing.

The provisioning node from `aligner_species.sh`, `http://35.201.96.177/` will return this

```
Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds.
```

Previously, it would show the stock Apache2 success page. Is this something to be concerned about?

EDIT: Very strange error, could it be apache's updates or something causing issues? There were provision nodes that I deployed that still showed the above error after overnight waits, and another one I deployed 1 hour ago suddenly started working after Lachlan clicked the link...

**Comment by obsh** [comment]
Currently, alignment cluster provisioning is refactored to set up internal load-balancer without exposing alignment endpoint to the internet.
Therefore, it's hard to reproduce error that you've observed.
I'm closing issue for now.
