### ISSUE TITLE
add options for alignment batch size and for BWA arguments

### ISSUE THREAD

**Issue by obsh** [allenday/nanostream-dataflow#90]
In order to make pipeline more flexible, make following values configurable through options:
1. Alignment batch size:
https://github.com/allenday/nanostream-dataflow/blob/master/NanostreamDataflowMain/src/main/java/com/google/allenday/nanostream/NanostreamApp.java#L53
with default value: **2000**
2. BWA arguments:
add `content.put("args", bwaArguments);` after this line:
https://github.com/allenday/nanostream-dataflow/blob/master/NanostreamDataflowMain/src/main/java/com/google/allenday/nanostream/aligner/MakeAlignmentViaHttpFn.java#L43
default value: **'-t 4'** which means - 4 threads by default

**Comment by Pseverin** [comment]
Added in https://github.com/allenday/nanostream-dataflow/pull/95
