### ISSUE TITLE
Embed folder or .fastq name as part of Firestore document name

### ISSUE THREAD

**Issue by Firedrops** [allenday/nanostream-dataflow#93]
Would aid with identifying runs. For example, 

a `AB_CDE.fastq` will generate something like `AB_CDE-2019-02-26T12-34-56UTC`, instead of or in addition to `resultDocument...`. 

and a folder upload with multiple `.fastq`, if it's possible to detect this, be named with the folder's name.

Maybe the timestamp can be less verbose if we use the input names as identifiers.

This would also help with generating more intuitive URLs in #57.

**Comment by Pseverin** [comment]
Added in https://github.com/allenday/nanostream-dataflow/pull/96 . Now we have functionality of grouping results by source folder of GCS bucket.
For example, if you add next fastq files
```
gs://test_bucket/folder_1/1.fastq
gs://test_bucket/folder_1/2.fastq
gs://test_bucket/folder_2/3.fastq
gs://test_bucket/folder_2/4.fastq
```
you will have two result documents, for `folder_1` and `folder_2`
